# coding: utf-8

"""
    AvaTax REST API

    The AvaTax REST API exposes the most commonly used available for interacting with the AvaTax service, allowing calculation of tax, modification of documents, and validation of addresses. If you're unsure of which API to use, a full comparison of the differences between the functionality provided by our REST and SOAP interfaces is documented [here](http://developer.avalara.com/avatax/soap-or-rest/). The [SOAP API reference](http://developer.avalara.com/avatax/api-reference/tax/soap) is also available.

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.models.doc_code import DocCode


class TestDocCode(unittest.TestCase):
    """ DocCode unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDocCode(self):
        """
        Test DocCode
        """
        model = swagger_client.models.doc_code.DocCode()


if __name__ == '__main__':
    unittest.main()
