# coding: utf-8

"""
    AvaTax REST API

    The AvaTax REST API exposes the most commonly used available for interacting with the AvaTax service, allowing calculation of tax, modification of documents, and validation of addresses. If you're unsure of which API to use, a full comparison of the differences between the functionality provided by our REST and SOAP interfaces is documented [here](http://developer.avalara.com/avatax/soap-or-rest/). The [SOAP API reference](http://developer.avalara.com/avatax/api-reference/tax/soap) is also available.

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import models into sdk package
from .models.address import Address
from .models.address_1 import Address1
from .models.cancel_tax_request import CancelTaxRequest
from .models.cancel_tax_response import CancelTaxResponse
from .models.cancel_tax_result import CancelTaxResult
from .models.cancel_tax_unauthorized_error import CancelTaxUnauthorizedError
from .models.country import Country
from .models.doc_code import DocCode
from .models.error_result_code import ErrorResultCode
from .models.estimate_tax_error import EstimateTaxError
from .models.estimate_tax_result import EstimateTaxResult
from .models.get_tax_error import GetTaxError
from .models.get_tax_request import GetTaxRequest
from .models.get_tax_result import GetTaxResult
from .models.line import Line
from .models.message import Message
from .models.result_code import ResultCode
from .models.tax_address import TaxAddress
from .models.tax_detail import TaxDetail
from .models.tax_line import TaxLine
from .models.tax_override import TaxOverride
from .models.validate_result import ValidateResult
from .models.validate_result_error import ValidateResultError

# import apis into sdk package
from .apis.default_api import DefaultApi

# import ApiClient
from .api_client import ApiClient

from .configuration import Configuration

configuration = Configuration()
